# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autofix_commit_msg: "chore(pre-commit.ci): auto fixes from pre-commit hooks"
  autoupdate_commit_msg: "chore(pre-commit.ci): pre-commit autoupdate"
  autoupdate_schedule: "monthly"
fail_fast: false
repos:
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
        types_or: [json, yaml]
  # - repo: local
  #   hooks:
  #     - id: fmt
  #       name: cargo fmt
  #       files: ^.*\.(rs|toml)$
  #       language: rust
  #       entry: cargo fmt
  #       pass_filenames: false
  # - repo: https://github.com/djlint/djLint
  #   rev: v1.36.4
  #   hooks:
  #     - id: djlint
  #       name: djLint
  #       files: \.(html|jinja|j2)$
  #       args: ["--reformat", "--lint"]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.0
    hooks:
      - id: markdownlint-cli2
        name: markdownlint
        files: \.md$
        args: ["--fix"]
  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.3.0
  #   hooks:
  #     - id: codespell
  #       name: codespell
  #       files: \.(md|txt)$
  #       args:
  #         - "--check-hidden"
  #         - "--skip=*.lock,*.svg"

